version: "3.7"

services:
  app:
    build: .
    ports:
      - "8090:8090"
    networks:
      - my-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jagadeeshDB
      POSTGRES_USER: jagadeeswar
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    networks:
      - my-network
    volumes:
      - postgres_department_data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres_department_data:


